version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    redis-server:
        image: 'redis:latest'
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - '3050:80'
        depends_on:
            - api
            - client
            

    
    api: 
        stdin_open: true
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis-server
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABAS=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - postgres
            - redis-server
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        environment:
            - REDIS_HOST=redis-server
            - REDIS_PORT=6379
        
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
